FR_MODE = "ACK ON ERROR"
RETRANSMISSION_TIMEOUT = 100  # in seconds
SIGFOX_DL_TIMEOUT = 60  # in seconds
INACTIVITY_TIMEOUT = 500  # in seconds
MAX_ACK_REQUESTS = 5
L2_WORD_SIZE = 8
DELAY_BETWEEN_FRAGMENTS = 10  # in seconds

# Sender config
ENABLE_MAX_ACK_REQUESTS = True

# Receiver config
RESET_DATA_AFTER_REASSEMBLY = False
CHECK_FOR_CALLBACK_RETRIES = True
DISABLE_INACTIVITY_TIMEOUT = False

RECEIVER_URL = "http://localhost:5000/receive"
